export const actionName = {
    OPEN_SIDEBAR: 'OPEN_SIDEBAR',
    STATUS_LOGIN: 'STATUS_LOGIN',
    STATUS_LOADING: 'STATUS_LOADING',
    TEXT_ALERT: 'TEXT_ALERT',
    MODE_LIGHT: 'MODE_LIGHT',
    OPEN_AND_CLOSE_CHAT: 'OPEN_AND_CLOSE_CHAT',
    SEND_MESSAGE: 'SEND_MESSAGE',
    CURRENT_USER: 'CURRENT_USER',
    UPDATE_CURRENT_MSG: 'UPDATE_CURRENT_MSG',
    USERS_CONTACTED: 'USERS_CONTACTED',
    OPEN_AND_GET_MSG: 'OPEN_AND_GET_MSG'
}